// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/map-ui/MapDesignA.tsx": () => import("../components/mockups/map-ui/MapDesignA.tsx"),
  "./components/mockups/map-ui/MapDesignB.tsx": () => import("../components/mockups/map-ui/MapDesignB.tsx"),
  "./components/mockups/map-ui/MapDesignC.tsx": () => import("../components/mockups/map-ui/MapDesignC.tsx")
};
